<a href="https://colab.research.google.com/github/BU-Spark/ds-ciss-predictive-homlessness/blob/data-cleaning-feature/fix_targets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
base_path = '/content/drive/My Drive/DS539'

df_path = f'{base_path}/CISS_Final_Dataset.csv'

In [5]:
import pandas as pd

final_df = pd.read_csv(df_path)

In [7]:
final_df.head()

,CoC_Number,Year,weighted median income,weighted median rent,total population,tract count,CoC Name,Overall Homeless,Sheltered Total Homeless,Unsheltered Homeless,Overall Homeless Individuals,Overall Homeless People in Families,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,Average Temperature,"Beds (ES, TH, SH)"
0,AK-500,2007,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,974.0,842.0,132.0,696.0,278.0,8.298238,7.425172,40.858279,42.153397,7.583368,5.5,884.0
1,AK-500,2008,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1023.0,921.0,102.0,695.0,328.0,8.298238,7.425172,40.858279,42.153397,7.583368,0.4,899.0
2,AK-500,2009,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1267.0,1110.0,157.0,821.0,446.0,8.298238,7.425172,40.858279,42.153397,7.583368,-0.2,877.0
3,AK-500,2010,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1231.0,1113.0,118.0,740.0,491.0,8.298238,7.425172,40.858279,42.153397,7.583368,1.5,990.0
4,AK-500,2011,80808.699781,1037.436470,287390.0,55.0,Anchorage CoC,1223.0,1082.0,141.0,794.0,429.0,8.504627,7.073878,42.293547,42.845948,7.593841,7.0,1056.0

In [8]:
final_df = final_df.drop(columns=['tract count'])

cols_to_modify = [
    'Sheltered Total Homeless',
    'Unsheltered Homeless',
    'Overall Homeless Individuals',
    'Overall Homeless People in Families',
    'Overall Homeless'
]

for col in cols_to_modify:
    final_df[col] = (final_df[col] / final_df['total population']) * 1000

In [9]:
final_df.head()

,CoC_Number,Year,weighted median income,weighted median rent,total population,CoC Name,Overall Homeless,Sheltered Total Homeless,Unsheltered Homeless,Overall Homeless Individuals,Overall Homeless People in Families,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,Average Temperature,"Beds (ES, TH, SH)"
0,AK-500,2007,78328.533122,1062.638009,284267.0,Anchorage CoC,3.426356,2.962004,0.464352,2.448402,0.977954,8.298238,7.425172,40.858279,42.153397,7.583368,5.5,884.0
1,AK-500,2008,78328.533122,1062.638009,284267.0,Anchorage CoC,3.598729,3.239912,0.358818,2.444885,1.153845,8.298238,7.425172,40.858279,42.153397,7.583368,0.4,899.0
2,AK-500,2009,78328.533122,1062.638009,284267.0,Anchorage CoC,4.457077,3.904780,0.552298,2.888130,1.568948,8.298238,7.425172,40.858279,42.153397,7.583368,-0.2,877.0
3,AK-500,2010,78328.533122,1062.638009,284267.0,Anchorage CoC,4.330436,3.915333,0.415103,2.603186,1.727249,8.298238,7.425172,40.858279,42.153397,7.583368,1.5,990.0
4,AK-500,2011,80808.699781,1037.436470,287390.0,Anchorage CoC,4.255541,3.764919,0.490622,2.762796,1.492745,8.504627,7.073878,42.293547,42.845948,7.593841,7.0,1056.0

In [10]:
final_df.to_csv('CISS_final_df2.csv', index=False)